name: Deploy website

on:
  push:
<<<<<<< HEAD
	branches:
	  - main
=======
    branches:
      - main
>>>>>>> main
  pull_request:

jobs:
  deploy:
<<<<<<< HEAD
	runs-on: ubuntu-22.04
	steps:
	  - uses: actions/checkout@v3
	  - name: Deploy
		uses: peaceiris/actions-gh-pages@v3
		if: github.ref == 'refs/heads/main'
		with:
		  github_token: ${{ secrets.GITHUB_TOKEN }}
		  publish_dir: ./src # deploy src folder
=======
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./src # deploy src folder
>>>>>>> main
